import type { Car, Testimonial } from './types'

// SU7 shared color variants — drop matching files into /public/images/cars/
const SU7_CDN = 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/su7_20260319/pc'

const SU7_COLOR_VARIANTS = [
  { name: 'Capri Blue',       hex: '#2B9FE8', image: `${SU7_CDN}/6-1.png` },
  { name: 'Crimson Red',      hex: '#C62828', image: `${SU7_CDN}/6-2.png` },
  { name: 'Forest Green',     hex: '#1A4A35', image: `${SU7_CDN}/6-3.png` },
  { name: 'Twilight Mauve',   hex: '#8B7389', image: `${SU7_CDN}/6-4.png` },
  { name: 'Vivid Magenta',    hex: '#C8185A', image: `${SU7_CDN}/6-5.png` },
  { name: 'Starlight Silver', hex: '#B0B4BA', image: `${SU7_CDN}/6-6.png` },
  { name: 'Pearl White',      hex: '#F0EEE9', image: `${SU7_CDN}/6-7.png` },
  { name: 'Champagne Rose',   hex: '#C8A882', image: `${SU7_CDN}/6-8.png` },
]

export const CARS: Car[] = [
  {
    id: '1',
    slug: 'xiaomi-su7-standard',
    brand: 'Xiaomi',
    model: 'SU7',
    fullName: 'Xiaomi SU7',
    year: 2024,
    bodyType: 'Sedan',
    fuelType: 'Electric',
    doors: 4,
    condition: 'New',
    range: '700 km',
    acceleration: '5.28s (0-100)',
    topSpeed: '210 km/h',
    horsepower: '295 HP',
    battery: '73.6 kWh',
    pricePerMonth: { 12: 1499, 24: 1299, 36: 1099 },
    images: [
      `${SU7_CDN}/6-1.png`,
    ],
    colors: ['Capri Blue', 'Crimson Red', 'Forest Green', 'Twilight Mauve', 'Vivid Magenta', 'Starlight Silver', 'Pearl White', 'Champagne Rose'],
    colorVariants: SU7_COLOR_VARIANTS,
    features: [
      'Xiaomi HyperOS in-car system',
      'Advanced driver assistance (NOA)',
      '16.1" 3K central display',
      'Xiaomi Pilot Pro driver assistance',
      'V2L vehicle-to-load charging',
      'Full glass panoramic roof',
    ],
    badge: 'Best Seller',
    description: 'The Xiaomi SU7 redefines what an electric sedan can be. Combining breathtaking design with cutting-edge technology, it delivers a 700 km range, Xiaomi HyperOS integration, and a 5.28s 0-100 km/h sprint — all in a beautifully crafted package.',
    isFeatured: true,
  },
  {
    id: '2',
    slug: 'xiaomi-su7-pro',
    brand: 'Xiaomi',
    model: 'SU7 Pro',
    fullName: 'Xiaomi SU7 Pro',
    year: 2024,
    bodyType: 'Sedan',
    fuelType: 'Electric',
    doors: 4,
    condition: 'New',
    range: '830 km',
    acceleration: '5.28s (0-100)',
    topSpeed: '210 km/h',
    horsepower: '295 HP',
    battery: '94.3 kWh',
    pricePerMonth: { 12: 1799, 24: 1599, 36: 1399 },
    images: [
      `${SU7_CDN}/6-2.png`,
    ],
    colors: ['Capri Blue', 'Crimson Red', 'Forest Green', 'Twilight Mauve', 'Vivid Magenta', 'Starlight Silver', 'Pearl White', 'Champagne Rose'],
    colorVariants: SU7_COLOR_VARIANTS,
    features: [
      'Extended 830 km range (CLTC)',
      '94.3 kWh CATL Qilin battery',
      'Xiaomi HyperOS in-car system',
      'Advanced NOA navigation on autopilot',
      '16.1" 3K central display',
      'Enhanced Xiaomi Pilot Pro',
    ],
    badge: 'Extended Range',
    description: 'The SU7 Pro pushes the boundaries further with an impressive 830 km CLTC range. Equipped with the next-gen CATL Qilin battery, this is the perfect choice for those who demand more from every charge.',
    isFeatured: true,
  },
  {
    id: '3',
    slug: 'xiaomi-su7-max',
    brand: 'Xiaomi',
    model: 'SU7 Max',
    fullName: 'Xiaomi SU7 Max',
    year: 2024,
    bodyType: 'Sedan',
    fuelType: 'Electric',
    doors: 4,
    condition: 'New',
    range: '800 km',
    acceleration: '2.78s (0-100)',
    topSpeed: '265 km/h',
    horsepower: '673 HP',
    battery: '101 kWh',
    pricePerMonth: { 12: 2699, 24: 2399, 36: 2199 },
    images: [
      `${SU7_CDN}/6-7.png`,
    ],
    colors: ['Pearl White', 'Crimson Red', 'Forest Green', 'Twilight Mauve', 'Starlight Silver'],
    colorVariants: [
      { name: 'Pearl White',      hex: '#F0EEE9', image: `${SU7_CDN}/6-7.png` },
      { name: 'Crimson Red',      hex: '#C62828', image: `${SU7_CDN}/6-2.png` },
      { name: 'Forest Green',     hex: '#1A4A35', image: `${SU7_CDN}/6-3.png` },
      { name: 'Twilight Mauve',   hex: '#8B7389', image: `${SU7_CDN}/6-4.png` },
      { name: 'Starlight Silver', hex: '#B0B4BA', image: `${SU7_CDN}/6-6.png` },
    ],
    features: [
      'Dual motor AWD — 673 HP combined',
      '0-100 km/h in just 2.78 seconds',
      '265 km/h electronically limited top speed',
      '101 kWh battery pack',
      'Brembo brakes (6-piston front)',
      'Xiaomi Pilot Max full self-driving suite',
    ],
    badge: 'Performance',
    description: 'The SU7 Max is a performance titan. With dual motors delivering 673 HP and a 0-100 sprint of 2.78 seconds, it competes with the world\'s fastest sedans while offering an 800 km range — pure Xiaomi engineering excellence.',
    isFeatured: true,
  },
  {
    id: '4',
    slug: 'xiaomi-su7-ultra',
    brand: 'Xiaomi',
    model: 'SU7 Ultra',
    fullName: 'Xiaomi SU7 Ultra',
    year: 2025,
    bodyType: 'Sedan',
    fuelType: 'Electric',
    doors: 4,
    condition: 'New',
    range: '630 km',
    acceleration: '1.98s (0-100)',
    topSpeed: '350 km/h',
    horsepower: '1526 HP',
    battery: '101 kWh',
    pricePerMonth: { 12: 4999, 24: 4499, 36: 3999 },
    images: [
      '/images/cars/su7-ultra.jpg',
    ],
    colors: ['Onyx Black', 'Sage Green', 'Titanium Silver', 'Racing Red'],
    colorVariants: [
      { name: 'Onyx Black',      hex: '#1C1C1E', image: '/images/cars/su7-ultra.jpg' },
      { name: 'Sage Green',      hex: '#7D8C4A', image: '/images/cars/su7-olive.jpg' },
      { name: 'Titanium Silver', hex: '#9EA5AD', image: '/images/cars/su7-silver.jpg' },
      { name: 'Racing Red',      hex: '#C62828', image: '/images/cars/su7-red.jpg' },
    ],
    features: [
      'Triple motor — 1526 HP hypercar performance',
      '0-100 km/h in an incredible 1.98 seconds',
      '350 km/h electronically limited top speed',
      'Nürburgring Nordschleife lap record holder',
      'Xiaomi Pilot Ultra advanced ADAS suite',
      'Carbon fibre body elements & race-spec aerodynamics',
    ],
    badge: 'Nürburgring Record',
    description: 'The SU7 Ultra is Xiaomi\'s ultimate statement. A triple-motor hypercar sedan with 1,526 HP, 0-100 in 1.98 seconds, and a Nürburgring record. This is electric performance at its most extreme.',
    isFeatured: true,
  },
  {
    id: '5',
    slug: 'xiaomi-yu7',
    brand: 'Xiaomi',
    model: 'YU7',
    fullName: 'Xiaomi YU7',
    year: 2025,
    bodyType: 'SUV',
    fuelType: 'Electric',
    doors: 4,
    condition: 'New',
    range: '760 km',
    acceleration: '3.23s (0-100)',
    topSpeed: '253 km/h',
    horsepower: '681 HP',
    battery: '96.3 kWh',
    pricePerMonth: { 12: 2199, 24: 1899, 36: 1699 },
    images: [
      'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.6.png',
    ],
    colors: ['Pearl White', 'Solar Orange', 'Shadow Blue', 'Flowing Gold Pink', 'Cambrian Gray', 'Ocean Blue', 'Titanium', 'Champagne'],
    colorVariants: [
      { name: 'Pearl White',       hex: '#E8E8E4', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.1.png' },
      { name: 'Solar Orange',      hex: '#D4520A', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.2.png' },
      { name: 'Shadow Blue',       hex: '#4A8FA0', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.3.png' },
      { name: 'Flowing Gold Pink', hex: '#B8788A', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.4.png' },
      { name: 'Cambrian Gray',     hex: '#3A4A5C', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.5.png' },
      { name: 'Ocean Blue',        hex: '#1A4A8C', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.6.png' },
      { name: 'Titanium Metal',    hex: '#8C8C8A', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.7.png' },
      { name: 'Champagne Gold',    hex: '#C8A882', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.8.png' },
    ],
    features: [
      'Dual motor AWD — 681 HP',
      '0-100 km/h in 3.23 seconds',
      '760 km range (CLTC)',
      'Air suspension with intelligent levelling',
      'Panoramic glass roof with UV protection',
      'Xiaomi HyperOS with 3-screen cockpit',
    ],
    badge: 'New 2025',
    description: 'The Xiaomi YU7 SUV combines extraordinary performance with premium everyday practicality. A 760 km range, dual-motor AWD with 681 HP, and a stunning interior make this the SUV that redefines the segment.',
    isFeatured: true,
  },
  {
    id: '7',
    slug: 'xiaomi-yu7-pro',
    brand: 'Xiaomi',
    model: 'YU7 Pro',
    fullName: 'Xiaomi YU7 Pro',
    year: 2025,
    bodyType: 'SUV',
    fuelType: 'Electric',
    doors: 4,
    condition: 'New',
    range: '820 km',
    acceleration: '4.87s (0-100)',
    topSpeed: '220 km/h',
    horsepower: '299 HP',
    battery: '96.3 kWh',
    pricePerMonth: { 12: 1899, 24: 1699, 36: 1499 },
    images: [
      'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.3.png',
    ],
    colors: ['Shadow Blue', 'Pearl White', 'Solar Orange', 'Cambrian Gray', 'Titanium Metal', 'Champagne Gold'],
    colorVariants: [
      { name: 'Shadow Blue',       hex: '#4A8FA0', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.3.png' },
      { name: 'Pearl White',       hex: '#E8E8E4', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.1.png' },
      { name: 'Solar Orange',      hex: '#D4520A', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.2.png' },
      { name: 'Cambrian Gray',     hex: '#3A4A5C', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.5.png' },
      { name: 'Titanium Metal',    hex: '#8C8C8A', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.7.png' },
      { name: 'Champagne Gold',    hex: '#C8A882', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.8.png' },
    ],
    features: [
      'Single motor RWD — 299 HP',
      'Industry-leading 820 km range (CLTC)',
      '4.87s 0-100 km/h',
      'Air suspension with intelligent levelling',
      'Panoramic glass roof with UV protection',
      'Xiaomi HyperOS with 3-screen cockpit',
    ],
    badge: 'Long Range',
    description: 'The YU7 Pro maximises efficiency with a single-motor RWD setup and class-leading 820 km range. Ideal for those who want the spacious YU7 experience with the lowest running costs and longest journeys between charges.',
    isFeatured: false,
  },
  {
    id: '8',
    slug: 'xiaomi-yu7-max',
    brand: 'Xiaomi',
    model: 'YU7 Max',
    fullName: 'Xiaomi YU7 Max',
    year: 2025,
    bodyType: 'SUV',
    fuelType: 'Electric',
    doors: 4,
    condition: 'New',
    range: '680 km',
    acceleration: '2.9s (0-100)',
    topSpeed: '253 km/h',
    horsepower: '840 HP',
    battery: '101 kWh',
    pricePerMonth: { 12: 3599, 24: 3199, 36: 2899 },
    images: [
      'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.5.png',
    ],
    colors: ['Cambrian Gray', 'Pearl White', 'Shadow Blue', 'Flowing Gold Pink', 'Ocean Blue', 'Solar Orange'],
    colorVariants: [
      { name: 'Cambrian Gray',     hex: '#3A4A5C', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.5.png' },
      { name: 'Pearl White',       hex: '#E8E8E4', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.1.png' },
      { name: 'Shadow Blue',       hex: '#4A8FA0', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.3.png' },
      { name: 'Flowing Gold Pink', hex: '#B8788A', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.4.png' },
      { name: 'Ocean Blue',        hex: '#1A4A8C', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.6.png' },
      { name: 'Solar Orange',      hex: '#D4520A', image: 'https://s1.xiaomiev.com/activity-outer-assets/0328/images/yu7_20250626/pc/9.2.png' },
    ],
    features: [
      'Tri-motor AWD — 840 HP combined',
      '0-100 km/h in 2.9 seconds',
      '253 km/h electronically limited top speed',
      '101 kWh battery — 680 km range (CLTC)',
      'Adaptive air suspension with sport mode',
      'Xiaomi Pilot Max full self-driving suite',
    ],
    badge: 'Performance SUV',
    description: 'The YU7 Max is Xiaomi\'s performance SUV flagship. Tri-motor AWD delivers 840 HP and a supercar-rivalling 2.9-second 0-100 sprint, wrapped in the spacious, tech-laden YU7 body. The fastest SUV in its class.',
    isFeatured: false,
  },
  {
    id: '6',
    slug: 'xiaomi-su7-preowned',
    brand: 'Xiaomi',
    model: 'SU7',
    fullName: 'Xiaomi SU7 (Pre-Owned)',
    year: 2024,
    bodyType: 'Sedan',
    fuelType: 'Electric',
    doors: 4,
    condition: 'Pre-Owned',
    range: '700 km',
    acceleration: '5.28s (0-100)',
    topSpeed: '210 km/h',
    horsepower: '295 HP',
    battery: '73.6 kWh',
    pricePerMonth: { 12: 1199, 24: 999, 36: 849 },
    images: [
      '/images/cars/su7-silver.jpg',
    ],
    colors: ['Onyx Black', 'Porcelain White', 'Aqua Blue'],
    colorVariants: [
      { name: 'Onyx Black',      hex: '#1C1C1E', image: '/images/cars/su7-black.jpg' },
      { name: 'Porcelain White', hex: '#F0EEE9', image: '/images/cars/su7-white.jpg' },
      { name: 'Aqua Blue',       hex: '#3B9ED8', image: '/images/cars/su7-blue.jpg' },
    ],
    features: [
      'Certified pre-owned inspection',
      'Xiaomi HyperOS',
      '16.1" 3K central display',
      'Full service history',
      'Remaining manufacturer warranty',
    ],
    badge: 'Pre-Owned',
    description: 'Certified pre-owned Xiaomi SU7 with full inspection history. All our pre-owned vehicles undergo a 160-point inspection and come with the remaining manufacturer warranty transferred.',
    isFeatured: false,
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Ahmed Al Mansouri',
    rating: 5,
    review: 'Leasing my Xiaomi SU7 through Xiaomi Leasing UAE was seamless. The process was fast, transparent, and the monthly payment fits perfectly into my budget. The car itself is incredible — I get compliments every single day.',
    car: 'Xiaomi SU7 Pro',
    location: 'Dubai, UAE',
    avatar: 'AM',
  },
  {
    id: '2',
    name: 'Sarah Thompson',
    rating: 5,
    review: 'As a business professional, I needed a premium car without the ownership hassle. The SU7 Max is extraordinary and the 24-month lease includes everything — insurance, registration, maintenance. Truly hassle-free.',
    car: 'Xiaomi SU7 Max',
    location: 'Abu Dhabi, UAE',
    avatar: 'ST',
  },
  {
    id: '3',
    name: 'Khalid Al Rashidi',
    rating: 5,
    review: 'The Xiaomi YU7 is the perfect family SUV. Huge space, incredible technology, and the lease terms from Xiaomi Leasing UAE are unbeatable. 36 months with full maintenance included — zero stress.',
    car: 'Xiaomi YU7',
    location: 'Sharjah, UAE',
    avatar: 'KR',
  },
  {
    id: '4',
    name: 'Priya Nair',
    rating: 5,
    review: 'I switched from a traditional car ownership model to leasing my SU7 and it was the best decision. No depreciation worries, full insurance, and the Xiaomi technology keeps getting better with every software update.',
    car: 'Xiaomi SU7',
    location: 'Dubai, UAE',
    avatar: 'PN',
  },
  {
    id: '5',
    name: 'Mohammed Al Zaabi',
    rating: 5,
    review: 'The SU7 Ultra is a dream car made real. Xiaomi Leasing UAE made it accessible with a flexible plan. Their team is professional, responsive, and genuinely committed to making the experience exceptional.',
    car: 'Xiaomi SU7 Ultra',
    location: 'Dubai, UAE',
    avatar: 'MZ',
  },
]
